#!/bin/sh
PREVIEW_ID="vifm_preview"

[ -z "$DISPLAY" ] && exit 1

[ -e "$UEBERZUG_FIFO" ] && {
	[ "$1" = "draw" ] && {
		PATH="$PWD/$6"
		[ -e "$PATH" ] || PATH="$6"

		printf "%s\n" '{ "action": "add", "identifier": "'"$PREVIEW_ID"'", "x": "'"$2"'", "y": "'"$3"'", "width": "'"$4"'", "height": "'"$5"'", "scaler": "fit_contain", "path": "'"$PATH"'" }' > "$UEBERZUG_FIFO"
	} || {
		[ "$1" = "clear" ] && {
			printf "%s\n" '{ "action": "remove", "identifier": "'"$PREVIEW_ID"'" }' > "$UEBERZUG_FIFO"
		}
	}
}
