#!/bin/sh

[ "$DISPLAY" ] || {
    PATH="$PWD/$6"
    [ -e "$PATH" ] || PATH="$6"

    /usr/bin/ffprobe -hide_banner -pretty "$PATH" 2>&1
    exit
}

[ "$1" = "draw" ] && {
    mkdir -p /tmp/vifm-thumbnails

    VIDEO_HASH=$(xxhsum "$6" | cut -d' ' -f1)
    THUMB_PATH="/tmp/vifm-thumbnails/$VIDEO_HASH.png"

    [ -e "$THUMB_PATH" ] || \
        ffmpegthumbnailer -m -i "$6" -o "$THUMB_PATH" -s 0

    vifm_img draw $2 $3 $4 $5 "$THUMB_PATH"
} || {
    vifm_img $@
}
