#!/bin/sh
PREVIEW_ID="vifm_preview"

[ -e "$UEBERZUG_FIFO" ] && {
	[ "$1" = "add" ] && {
		printf "%s\n" '{ "action": "add", "identifier": "'"$PREVIEW_ID"'", "x": "'"$2"'", "y": "'"$3"'", "width": "'"$4"'", "height": "'"$5"'", "scaler": "fit_contain", "path": "'"$PWD/$6"'" }' > "$UEBERZUG_FIFO"
	} || {
		printf "%s\n" '{ "action": "remove", "identifier": "'"$PREVIEW_ID"'" }' > "$UEBERZUG_FIFO"
	}
}

