#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30

bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true

bspc config normal_border_color			"#333333"
bspc config active_border_color			"#666666"
bspc config focused_border_color		"#6633FF"
bspc config presel_feedback_color		"#FF6633"

bspc config split_ratio					0.5
bspc config border_width				2
bspc config window_gap					25
bspc config top_padding					14
bspc config presel_feedback				true

#bspc config automatic_scheme			longest_side
#bspc config automatic_scheme			alternate
#bspc config automatic_scheme			spiral

#bspc config initial_polarity			first_child
#bspc config initial_polarity			second_child

bspc config borderless_monocle			true
bspc config gapless_monocle				true

bspc config swallow_first_click			false
bspc config focus_follows_pointer		true
bspc config pointer_modifier			shift
bspc config pointer_action1				move
bspc config pointer_action3				resize_side

bspc rule -a Screenkey manage=off

killall polybar
polybar -c ~/.config/polybar/config.ini main &

xsetroot -cursor_name left_ptr

