#!/bin/sh

# Vars
TERMINAL="foot"

# Wallpaper
swaybg -m fill -i /home/rin/Wallpapers/Yagate_Kimi_ni_Naru_Yuu_Touko_Lanterns_Crop.jpg &

# Start programs
#yambar &
waybar &
#dunst &
foot &

xrdb ~/.Xresources
unclutter --timeout 1 -b

cp ~/.bashrc /mnt/tmp/

## Mappings
riverctl map normal Mod1 Return spawn "${TERMINAL}" # Spawn terminal
riverctl map normal Mod1+Shift Q exit # Exit river
riverctl map normal Mod1 D spawn "bemenu-run -l 10 -i --nb '#111111' --nf '#ffffff' --ab '#111111' --af '#ffffff' --hb '#6600ff' --hf '#ffffff' --tb '#6600ff' --tf '#ffffff' --fb '#111111' --ff '#ffffff' "
riverctl map normal Mod1 L spawn "waylock --init-color '#000000' --input-color '#6633ff' --fail-color '#ff6600' || pkill river"
riverctl map normal Control F12 spawn "cd /home/rin/Screenshots; grim"
# Windows
riverctl map normal Mod1+Shift c close # Close window
riverctl map normal Mod1 J focus-view next     # Focus next win
riverctl map normal Mod1 K focus-view previous # Focus prev win
riverctl map normal Mod1+Shift J swap next     # Swap with next win
riverctl map normal Mod1+Shift K swap previous # Swap with prev win
riverctl map normal Mod1+Shift Return zoom # Bump to top of stack
# Screens
riverctl map normal Mod1 Period focus-output next     # Focus next scr
riverctl map normal Mod1 Comma  focus-output previous # Focus prev scr
riverctl map normal Mod1+Shift Period send-to-output next     # Move win to next scr
riverctl map normal Mod1+Shift Comma  send-to-output previous # Move win to prev scr
# Layout
riverctl map normal Mod1+Shift H send-layout-cmd rivercarro "main-ratio -0.05" # Decrease master ratio
riverctl map normal Mod1+Shift L send-layout-cmd rivercarro "main-ratio +0.05" # Increase master ratio
riverctl map normal Mod1+Shift I send-layout-cmd rivercarro "main-count +1" # Increate master win count
riverctl map normal Mod1+Shift D send-layout-cmd rivercarro "main-count -1" # Decrease master win count
riverctl map normal Mod1 T send-layout-cmd rivercarro "main-location left" # Tiling layout
riverctl map normal Mod1 M send-layout-cmd rivercarro "main-location monocle" # Monocle layout
# Toggle stuff
riverctl map normal Mod1+Shift Space toggle-float      # Toggle floating
riverctl map normal Mod1+Shift F     toggle-fullscreen # Toggle fullscreen
# Mouse
riverctl map-pointer normal Mod1 BTN_LEFT  move-view   # Mouse drag
riverctl map-pointer normal Mod1 BTN_RIGHT resize-view # Mouse resize

## Tags
# Access more tags than numbers on keyboard
riverctl declare-mode moretag
riverctl map normal  Mod1+Shift Grave enter-mode moretag # Enter moretag mode
riverctl map moretag Mod1+Shift Grave enter-mode normal  # Go back to normal mode

# Standard tags
for i in $(seq 1 10); do
    tags="$(( 1 << ($i - 1) ))"
    j="$(( ${i} % 10 ))"

    for mode in normal moretag; do
        riverctl map "${mode}" Mod1               "${j}" set-focused-tags    "${tags}" # Focus tag
        riverctl map "${mode}" Mod1+Shift         "${j}" set-view-tags       "${tags}" # Set tag on focused win
        riverctl map "${mode}" Mod1+Control       "${j}" toggle-focused-tags "${tags}" # Toggle tag focus
        riverctl map "${mode}" Mod1+Shift+Control "${j}" toggle-view-tags    "${tags}" # Toggle tag on focused win
    done
done
riverctl map normal Mod1 Tab focus-previous-tags

# Map tags 11-32 to keys A-V
for i in $(seq 11 32); do
    tags=$((1 << ($i - 1))) # Choose one tag
    KEY_CODE="$(( ${i} - 11 + $(printf "%d" "'A") ))"       # Choose letter based on tag number
    KEY_CHAR="$(printf "\\$(printf "%03o" "${KEY_CODE}")")" # Convert key code to ascii

    riverctl map moretag Mod1               "${KEY_CHAR}" set-focused-tags    $tags # Focus tag
    riverctl map moretag Mod1+Shift         "${KEY_CHAR}" set-view-tags       $tags # Set tag on focused win
    riverctl map moretag Mod1+Control       "${KEY_CHAR}" toggle-focused-tags $tags # Toggle tag focus
    riverctl map moretag Mod1+Shift+Control "${KEY_CHAR}" toggle-view-tags    $tags # Toggle tag on focused win
done

## Config
riverctl attach-mode top
riverctl background-color 0x111111

riverctl border-color-focused 0x6633FF
riverctl border-color-unfocused 0x444444
riverctl border-color-urgent 0xFF6600
riverctl border-width 2

riverctl focus-follows-cursor normal
riverctl set-cursor-warp disabled

# Set the default layout generator and start it.
riverctl default-layout rivercarro
rivercarro -main-location left -main-count 1 -main-ratio 0.6 -outer-gaps 0 -inner-gaps 0 -no-smart-gaps
