DEFAULT_FG="#D0D0D0"
WIN_DEFAULT_BG="#161616"

# Sway Window Borders
WIN_FOCUSED_BORDER="#78A9FF"
WIN_FOCUSED_TEXT_BG="${WIN_FOCUSED_BORDER}"
WIN_FOCUSED_TEXT_FG="#262626"
WIN_FOCUSED_INDICATOR="#82CFFF"
WIN_FOCUSED_CHILD_BORDER="${WIN_FOCUSED_BORDER}"

WIN_INACTIVE_BORDER="#525252"
WIN_INACTIVE_TEXT_BG="${WIN_INACTIVE_BORDER}"
WIN_INACTIVE_TEXT_FG="#F2F2F2"
WIN_INACTIVE_INDICATOR="${WIN_INACTIVE_BORDER}"
WIN_INACTIVE_CHILD_BORDER="${WIN_INACTIVE_BORDER}"

WIN_UNFOCUSED_BORDER="#393939"
WIN_UNFOCUSED_TEXT_BG="${WIN_UNFOCUSED_BORDER}"
WIN_UNFOCUSED_TEXT_FG="${DEFAULT_FG}"
WIN_UNFOCUSED_INDICATOR="${WIN_UNFOCUSED_BORDER}"
WIN_UNFOCUSED_CHILD_BORDER="${WIN_UNFOCUSED_BORDER}"

WIN_URGENT_BORDER="#EE5396"
WIN_URGENT_TEXT_BG="${WIN_URGENT_BORDER}"
WIN_URGENT_TEXT_FG="#F2F2F2"
WIN_URGENT_INDICATOR="${WIN_URGENT_BORDER}"
WIN_URGENT_CHILD_BORDER="${WIN_URGENT_BORDER}"

WIN_PLACEHOLDER_BORDER="#393939"
WIN_PLACEHOLDER_TEXT_BG="${WIN_DEFAULT_BG}"
WIN_PLACEHOLDER_TEXT_FG="#525252"
WIN_PLACEHOLDER_INDICATOR="#525252"
WIN_PLACEHOLDER_CHILD_BORDER="${WIN_PLACEHOLDER_BORDER}"

# Swaybar / Waybar
BAR_BG="#161616"
BAR_FG="${DEFAULT_FG}"
BAR_SEPARATOR="${DEFAULT_FG}"

BAR_WS_FOCUSED_BORDER="${WIN_FOCUSED_BORDER}"
BAR_WS_FOCUSED_TEXT_BG="${WIN_FOCUSED_TEXT_BG}"
BAR_WS_FOCUSED_TEXT_FG="${WIN_FOCUSED_TEXT_FG}"

# Occupied, but not focused
BAR_WS_INACTIVE_BORDER="${WIN_UNFOCUSED_BORDER}"
BAR_WS_INACTIVE_TEXT_BG="${WIN_UNFOCUSED_TEXT_BG}"
BAR_WS_INACTIVE_TEXT_FG="${WIN_UNFOCUSED_TEXT_FG}"

# Active on another monitor
BAR_WS_ACTIVE_BORDER="${WIN_INACTIVE_BORDER}"
BAR_WS_ACTIVE_TEXT_BG="${WIN_INACTIVE_TEXT_BG}"
BAR_WS_ACTIVE_TEXT_FG="${WIN_INACTIVE_TEXT_FG}"

BAR_WS_EMPTY_BORDER="#262626"
BAR_WS_EMPTY_TEXT_BG="${BAR_WS_EMPTY_BORDER}"
BAR_WS_EMPTY_TEXT_FG="${DEFAULT_FG}"

BAR_WS_URGENT_BORDER="${WIN_URGENT_BORDER}"
BAR_WS_URGENT_TEXT_BG="${WIN_URGENT_TEXT_BG}"
BAR_WS_URGENT_TEXT_FG="${WIN_URGENT_TEXT_FG}"

BAR_WS_BINDING_BORDER="#BE95FF"
BAR_WS_BINDING_TEXT_BG="${BAR_WS_BINDING_BORDER}"
BAR_WS_BINDING_TEXT_FG="#262626"

BAR_ACCENT_BG="${WIN_FOCUSED_TEXT_BG}"
BAR_ACCENT_FG="${WIN_FOCUSED_TEXT_FG}"
BAR_BLOCK="#262626"
BAR_BLOCK_ALT="#393939"

BAR_STATUS_GOOD="#78A9FF"
BAR_STATUS_WARN="#BE95FF"
BAR_STATUS_BAD="${WIN_URGENT_BORDER}"

# dmenu / bemenu
DMENU_NORMAL_BG="${BAR_BG}"
DMENU_NORMAL_FG="${BAR_FG}"
DMENU_SELECTED_BG="${WIN_FOCUSED_TEXT_BG}"
DMENU_SELECTED_FG="${WIN_FOCUSED_TEXT_FG}"

BEMENU_FILTER_BG="${DMENU_NORMAL_BG}"
BEMENU_FILTER_FG="${DMENU_NORMAL_FG}"
BEMENU_CURSOR_BG="${DMENU_NORMAL_BG}"
BEMENU_CURSOR_FG="${DMENU_NORMAL_FG}"
BEMENU_PROMPT_BG="${DMENU_SELECTED_BG}"
BEMENU_PROMPT_FG="${DMENU_SELECTED_FG}"
BEMENU_ALTERNATING_BG="${DMENU_NORMAL_BG}" # "#262626"
BEMENU_ALTERNATING_FG="${DMENU_NORMAL_FG}"
BEMENU_SELECTED_BG="${DMENU_SELECTED_FG}"
BEMENU_SELECTED_FG="${DMENU_SELECTED_BG}"
BEMENU_SCROLLBAR_BG="#262626"
BEMENU_SCROLLBAR_FG="#525252"
BEMENU_FEEDBACK_BG="${DMENU_SELECTED_FG}"
BEMENU_FEEDBACK_FG="${DMENU_SELECTED_BG}"
