DEFAULT_FG="#EEEEEE"
WIN_DEFAULT_BG="#111111"

# Sway Window Borders
WIN_FOCUSED_BORDER="#7755FF"
WIN_FOCUSED_TEXT_BG="${WIN_FOCUSED_BORDER}"
WIN_FOCUSED_TEXT_FG="${DEFAULT_FG}"
WIN_FOCUSED_INDICATOR="#55EFFF"
WIN_FOCUSED_CHILD_BORDER="${WIN_FOCUSED_BORDER}"

WIN_INACTIVE_BORDER="#555555"
WIN_INACTIVE_TEXT_BG="${WIN_INACTIVE_BORDER}"
WIN_INACTIVE_TEXT_FG="${DEFAULT_FG}"
WIN_INACTIVE_INDICATOR="${WIN_INACTIVE_BORDER}"
WIN_INACTIVE_CHILD_BORDER="${WIN_INACTIVE_BORDER}"

WIN_UNFOCUSED_BORDER="#333333"
WIN_UNFOCUSED_TEXT_BG="${WIN_UNFOCUSED_BORDER}"
WIN_UNFOCUSED_TEXT_FG="${DEFAULT_FG}"
WIN_UNFOCUSED_INDICATOR="${WIN_UNFOCUSED_BORDER}"
WIN_UNFOCUSED_CHILD_BORDER="${WIN_UNFOCUSED_BORDER}"

WIN_URGENT_BORDER="#FF6600"
WIN_URGENT_TEXT_BG="${WIN_URGENT_BORDER}"
WIN_URGENT_TEXT_FG="${DEFAULT_FG}"
WIN_URGENT_INDICATOR="${WIN_URGENT_BORDER}"
WIN_URGENT_CHILD_BORDER="${WIN_URGENT_BORDER}"

WIN_PLACEHOLDER_BORDER="#333333"
WIN_PLACEHOLDER_TEXT_BG="#000000"
WIN_PLACEHOLDER_TEXT_FG="#555555"
WIN_PLACEHOLDER_INDICATOR="#555555"
WIN_PLACEHOLDER_CHILD_BORDER="${WIN_PLACEHOLDER_BORDER}"

# Swaybar / Waybar
BAR_BG="#111111"
BAR_FG="${DEFAULT_FG}"
BAR_SEPARATOR="${DEFAULT_FG}"

BAR_WS_FOCUSED_BORDER="${WIN_FOCUSED_BORDER}"
BAR_WS_FOCUSED_TEXT_BG="${WIN_FOCUSED_TEXT_BG}"
BAR_WS_FOCUSED_TEXT_FG="${WIN_FOCUSED_TEXT_FG}"

# Occupied, but not focused
BAR_WS_INACTIVE_BORDER="${WIN_UNFOCUSED_BORDER}"
BAR_WS_INACTIVE_TEXT_BG="${WIN_UNFOCUSED_TEXT_BG}"
BAR_WS_INACTIVE_TEXT_FG="${WIN_UNFOCUSED_TEXT_FG}"

# Active on another monitor
BAR_WS_ACTIVE_BORDER="${WIN_INACTIVE_BORDER}"
BAR_WS_ACTIVE_TEXT_BG="${WIN_INACTIVE_TEXT_BG}"
BAR_WS_ACTIVE_TEXT_FG="${WIN_INACTIVE_TEXT_FG}"

BAR_WS_EMPTY_BORDER="#222222"
BAR_WS_EMPTY_TEXT_BG="${BAR_WS_EMPTY_BORDER}"
BAR_WS_EMPTY_TEXT_FG="${DEFAULT_FG}"

BAR_WS_URGENT_BORDER="${WIN_URGENT_BORDER}"
BAR_WS_URGENT_TEXT_BG="${WIN_URGENT_TEXT_BG}"
BAR_WS_URGENT_TEXT_FG="${WIN_URGENT_TEXT_FG}"

BAR_WS_BINDING_BORDER="#7755FF" # or "#77CCFF"
BAR_WS_BINDING_TEXT_BG="${BAR_WS_BINDING_BORDER}"
BAR_WS_BINDING_TEXT_FG="${DEFAULT_FG}"

BAR_ACCENT_BG="${WIN_FOCUSED_TEXT_BG}"
BAR_ACCENT_FG="${WIN_FOCUSED_TEXT_FG}"
BAR_BLOCK="#222222"
BAR_BLOCK_ALT="#333333"

BAR_STATUS_GOOD="#33FF33"
BAR_STATUS_WARN="#FF7733"
BAR_STATUS_BAD="#FF3333"

# dmenu / bemenu
DMENU_NORMAL_BG="${BAR_BG}"
DMENU_NORMAL_FG="${BAR_FG}"
DMENU_SELECTED_BG="${WIN_FOCUSED_TEXT_BG}"
DMENU_SELECTED_FG="${WIN_FOCUSED_TEXT_FG}"

BEMENU_FILTER_BG="${DMENU_NORMAL_BG}"
BEMENU_FILTER_FG="${DMENU_NORMAL_FG}"
BEMENU_CURSOR_BG="${DMENU_NORMAL_BG}"
BEMENU_CURSOR_FG="${DMENU_NORMAL_FG}"
BEMENU_PROMPT_BG="${DMENU_SELECTED_BG}"
BEMENU_PROMPT_FG="${DMENU_SELECTED_FG}"
BEMENU_ALTERNATING_BG="${DMENU_NORMAL_BG}" # "#222222"
BEMENU_ALTERNATING_FG="${DMENU_NORMAL_FG}"
BEMENU_SELECTED_BG="${DMENU_SELECTED_FG}"
BEMENU_SELECTED_FG="${DMENU_SELECTED_BG}"
BEMENU_SCROLLBAR_BG="#222222"
BEMENU_SCROLLBAR_FG="#444444"
BEMENU_FEEDBACK_BG="${DMENU_SELECTED_FG}"
BEMENU_FEEDBACK_FG="${DMENU_SELECTED_BG}"
